### ISSUE TITLE
What happens if I use a OP_RETURN UTXo 

### ISSUE THREAD

**Issue by hedgepaybsc** [bitcoinjs/bitcoinjs-lib#1893]
What should happen in the following example:

```
Tx:
 - input_0: utxo with OP_RETURN (unspendable)
 - input_1: valid utxo (1000 sats)
 
 - output_0:  valid address and value of 900 sats
```

Will this tx be accepted by the mempool?
